name: "✍️ ​ ​Suggest Changes"
description: Help us improve the roadmaps by suggesting changes
labels: [suggestion]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the roadmaps with your suggestions.
  - type: input
    id: url
    attributes:
      label: Roadmap URL
      description: Please provide the URL of the roadmap you are suggesting changes to.
      placeholder: https://roadmap.sh
    validations:
      required: true
  - type: textarea
    id: roadmap-suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest?
      placeholder: Enter your suggestions here.
    validations:
      required: true