name: "🙏 ​ ​Submit a Roadmap"
description: Help us launch a new roadmap with your expertise.
labels: [roadmap contribution]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a roadmap! Please fill out the information below and we'll get back to you as soon as we can.
  - type: input
    id: roadmap-title
    attributes:
      label: What is the title of the roadmap you are submitting?
      placeholder: e.g. Roadmap to learn Data Science
    validations:
      required: true
  - type: textarea
    id: roadmap-description
    attributes:
      label: Roadmap Link
      description: Please create the roadmap [using our roadmap editor](https://twitter.com/kamrify/status/1708293162693767426) and submit the roadmap link.
      placeholder: |
          https://roadmap.sh/xyz
    validations:
      required: true
