name: "🤷‍♂️ ​ ​Something else"
description: If none of the above templates fit your needs, please use this template to submit your issue.
labels: []
assignees: []
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Detailed Description
      description: Please provide a detailed description of the issue.
    validations:
      required: true